export const GET_TODOS = "GET_TODOS";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";

export const CREATE_TODOS = "CREATE_TODOS";

export const CREATE_TODOS_SUCCESS = "CREATE_TODOS_SUCCESS";

export const TODOS_ERROR = "TODOS_ERROR";

export const COMPLETE_TODO = "COMPLETE_TODO";

export const COMPLETE_TODO_SUCCESS = "COMPLETE_TODO_SUCCESS";


